name: test
on: workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Install Pandoc
          uses: r-lib/actions/setup-pandoc@v2

        - name: Convert readme to html
          run: pandoc readme.md -o readme.html

        - name: Fetch Entry via Gravity Forms API
          env:
            GF_API_URL: ${{ secrets.ENTRY_URL }}
            GF_BASIC_AUTH: ${{ secrets.GF_BASIC_AUTH }}
          run: |
            curl -s -H "Authorization: Basic $GF_BASIC_AUTH" \
                  "$GF_API_URL" \
                  -o entry.json
        - name: Inject HTML into field 3
          run: |
            HTML_CONTENT=$(< readme.html)
            # Escape double quotes and backslashes for JSON
            ESCAPED_HTML=$(printf '%s' "$HTML_CONTENT" | sed 's/\\/\\\\/g; s/"/\\"/g')
            jq ".\"3\" = \"$ESCAPED_HTML\"" entry.json > updated_entry.json

        - name: Send updated entry back
          env:
            GF_API_URL: ${{ secrets.ENTRY_URL }}
            GF_BASIC_AUTH: ${{ secrets.GF_BASIC_AUTH }}
          run: |
             curl -X PUT \
                -H "Authorization: Basic $GF_BASIC_AUTH" \
                -H "Content-Type: application/json" \
                --data @updated_entry.json \
                "$GF_API_URL"