name: update-directory.yml
on:
  workflow_dispatch: # manual
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - .gitignore

jobs:
  updateDescription:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Convert readme to html
        run: pandoc readme.md -f gfm -t html -s -o readme.html --no-highlight

      - name: Fetch Entry via Gravity Forms API
        env:
          GF_API_URL: ${{ secrets.ENTRY_URL }}
          GF_BASIC_AUTH: ${{ secrets.GF_BASIC_AUTH }}
        run: |
          curl -s -H "Authorization: Basic $GF_BASIC_AUTH" \
               "$GF_API_URL" \
               -o entry.json

      - name: Inject HTML into field 3
        run: |
          HTML_CLEAN=$(sed 's/"/\\"/g' README.html)
          jq --arg html "$HTML_CLEAN" '.["3"] = $html' entry.json > updated_entry.json


      - name: Send updated entry back
        env:
          GF_API_URL: ${{ secrets.ENTRY_URL }}
          GF_BASIC_AUTH: ${{ secrets.GF_BASIC_AUTH }}
        run: |
          curl -X PUT \
               -H "Authorization: Basic $GF_BASIC_AUTH" \
               -H "Content-Type: application/json" \
               --data @updated_entry.json \
               "$GF_API_URL"


# TODO edit entry with new description and submit form that snippet was updated