name: update-directory.yml
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - .gitignore

jobs:
  updateDescription:
    runs-on: ubuntu-latest
    steps:
      - name: submit form
        env:
          GF_API_URL: ${{ secrets.GF_UPDATE_WEBHOOK_URL }}
          COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
        run: |

          JSON_PAYLOAD=$(jq -n \
                --arg commit_msg "$COMMIT_MESSAGE" \
                '{input_1: "GFSearch Shortcode", input_3: $commit_msg}')

          curl -X POST "$GF_API_URL" \
                -H "Content-Type: application/json" \
                -d "$JSON_PAYLOAD"
                