name: update-directory.yml
on:
  workflow_dispatch: # manual
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - .gitignore

jobs:
  updateDescription:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Convert readme to html
        run: pandoc readme.md -f gfm -t html -s -o readme.html --no-highlight


# TODO edit entry with new description and submit form that snippet was updated