name: workflow.yml
on: workflow_dispatch

jobs:
  get_entry:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Entry via Gravity Forms API
        env:
          GF_API_URL: ${{ secrets.ENTRY_URL }}
          GF_BASIC_AUTH: ${{ secrets.GF_BASIC_AUTH }}
        run: |
          curl -s -H "Authorization: Basic $GF_BASIC_AUTH" \
               "$GF_API_URL" \
               -o entry.json

          echo "Entry contents:"
          cat entry.json
